RIPE-NCC/rpki-validator-3

src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java
Please take a look if the change is correct.
It's not exactly as described in the story, I had to make some adjustments.
=> Manifest error messages

rpki-validator/src/main/java/net/ripe/rpki/validator3/api/SearchTerm.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/rpkiobjects/RpkiObjectController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/api/SearchTermTest.java, ui-validator/e2e/app.po.ts, ui-validator/e2e/bgp.e2e-spec.ts, ui-validator/e2e/mock/data/bgp-preview/bgp-AS9737.json, ui-validator/e2e/mock/server.js, ui-validator/e2e/pages/BgpPage.ts, ui-validator/e2e/pages/RoasPage.ts, ui-validator/e2e/roas.e2e-spec.ts, ui-validator/src/app/bgp-preview/bgp-preview.component.ts, ui-validator/src/app/roas/roas.component.ts
Related to [#38](https://github.com/RIPE-NCC/rpki-validator-3/issues/38)
=> Issue #38 add direct link to query roas

rpki-validator/src/main/java/net/ripe/rpki/validator3/Validator3Application.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/StaticContentFixServlet.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roas/ExportsController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/config/PersistenceConfig.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/config/ServletConfig.java, rpki-validator/src/main/resources/application.properties, ui-validator/src/app/announcement-preview/announcement-preview.component.html, ui-validator/src/app/app.component.ts, ui-validator/src/app/app.module.ts, ui-validator/src/app/core/footer/footer.component.html, ui-validator/src/app/core/footer/footer.component.ts, ui-validator/src/app/ignore-filters/ignore-filters.service.ts, ui-validator/src/app/monitoring-ta/validation-details/validation-details.component.html, ui-validator/src/app/roas/roas.component.html, ui-validator/src/app/whitelist/whitelist.service.ts, ui-validator/src/index.html
This is to fix the issue https://github.com/RIPE-NCC/rpki-validator-3/issues/57
=> Fix servlet context path

rpki-validator/src/main/java/net/ripe/rpki/validator3/adapter/jpa/JPARpkiRepositories.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/rpkirepositories/RpkiRepositoriesController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/RpkiRepositories.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/adapter/jpa/JPARpkiRepositoriesTest.java, ui-validator/src/app/core/trust-anchors.service.ts, ui-validator/src/app/monitoring-ta/repositories/repositories.component.html, ui-validator/src/app/monitoring-ta/repositories/repositories.component.scss, ui-validator/src/app/monitoring-ta/repositories/repositories.component.ts, ui-validator/src/app/monitoring-ta/repositories/repositories.model.ts, ui-validator/src/assets/i18n/en.json
Deployed on prepdev, wait for twnic to fail and you can remove it, at some point it will come back on next ca tree validation.
=> Rpki 38 allow clean up failed repository

rpki-validator/src/main/java/net/ripe/rpki/validator3/adapter/jpa/JPARpkiObjects.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/adapter/jpa/JPARpkiRepositories.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/adapter/jpa/JPATrustAnchors.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/rpkirepositories/RpkiRepositoryService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/trustanchors/TrustAnchorService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/background/PrefetchRsyncRepositoryJob.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/background/ValidateRRDPRepositoriesJob.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/background/ValidateRsyncRepositoriesJob.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/background/ValidationScheduler.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/RpkiObjects.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/RpkiRepository.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpService.java, rpki-validator/src/main/resources/packaging/generic/conf/application-defaults.properties
Running this one on prepdev, startup from scratch seems reasonable, slightly more than 5 mins, and the last hour it has not yet produce any Unique Constraint Violation yet. *Crossing my finger*
=> Avoiding unique constraint violation

rpki-validator/src/main/java/net/ripe/rpki/validator3/api/health/HealthController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/util/Dates.java
health endpoint, and icinga should just look for OK. They should not run
this too often (just every hour should be fine).
=> Not sure how to put all these logic in icinga, so add the logic here in

rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java
Warnings were logged while the serial was actually higher.
=> Compare if new serial is higher than old serial

rpki-validator/pom.xml, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/util/RsyncFactory.java, rpki-validator/src/main/resources/application.properties
Add rsync proxy settings
```
rpki.validator.rsync.proxy.host=
rpki.validator.rsync.proxy.port=
```
analogous to http proxy settings.
=> Rsync proxy

rpki-rtr-server/pom.xml, rpki-validator/pom.xml, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/util/Dates.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/util/InstantWithoutNanos.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/validationruns/ValidationRunResource.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/cleanup/RpkiObjectCleanupService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/cleanup/ValidationRunCleanupService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/jobs/JobExecutor.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/Base.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/RpkiObject.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/RpkiRepository.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/validation/ValidationRun.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/encoding/custom/Coders.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/RpkiObjects.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/ValidationRuns.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/impl/RpkiObjectStore.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/impl/RpkiRepositoriesStore.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/impl/TrustAnchorStore.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/impl/ValidationRunsStore.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/cleanup/RpkiObjectCleanupServiceTest.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/cleanup/ValidationRunCleanupServiceTest.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/ta/TrustAnchorsFactory.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/storage/encoding/custom/RpkiRepositoryCoderTest.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/storage/encoding/custom/TrustAnchorCoderTest.java
=> make project JDK 11 compatible by truncating instants

.github/workflows/maven.yml, rpki-rtr-server/pom.xml, rpki-validator/pom.xml
=> run unit tests with Gitlab actions (after #131)

rpki-validator/src/main/java/net/ripe/rpki/validator3/config/ServletConfig.java
Try to explain the slightly convoluted regex.
=> Explain the regexes used for SPA behaviour

rpki-parent/pom.xml, rpki-rtr-server/pom.xml, rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/RtrServerApplication.java, rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/config/ApiConfig.java, rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/RtrCache.java, rpki-rtr-server/src/main/resources/application.properties, rpki-rtr-server/src/main/resources/packaging/generic/conf/application.properties, rpki-rtr-server/src/test/java/net/ripe/rpki/rtr/RtrServerTest.java, rpki-rtr-server/src/test/java/net/ripe/rpki/rtr/domain/RtrCacheTest.java, rpki-validator/Changelog.txt, rpki-validator/pom.xml, rpki-validator/src/main/java/net/ripe/rpki/validator3/Validator3Application.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/rpkirepositories/RpkiRepositoryService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/background/BackgroundJobs.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/config/ServletConfig.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/metrics/TrustAnchorMetricsService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/validation/ValidationRun.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/impl/TrustAnchorStore.java, rpki-validator/src/main/resources/application.properties, rpki-validator/src/main/resources/packaging/centos7/etc/rpki-validator-3/application.properties, rpki-validator/src/main/resources/packaging/deb/etc/rpki-validator-3/application.properties, rpki-validator/src/main/resources/packaging/generic/conf/application.properties
I'll run this for a while in my dev environment to make sure it works and resource usage is similar to last friday's branch.
Confirmed that test suite passes locally.
=> Upgrade to spring boot 2.2 and add prometheus endpoint

rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/adapter/validator/RefreshCacheController.java, rpki-rtr-server/src/main/resources/packaging/deb/control/control, rpki-validator/src/main/resources/packaging/deb/control/control
Managed to install this in xenial (vagrant).
=> We don't really need core utils.

rpki-validator/src/main/java/net/ripe/rpki/validator3/api/ModelPropertyDescriptions.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roas/ExportsController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/ValidatedRpkiObjects.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/RoaPrefix.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/RpkiObject.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/encoding/custom/RoaPrefixCoder.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/api/SearchTermTest.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/api/bgp/BgpPreviewServiceTest.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/cleanup/RpkiObjectCleanupServiceTest.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/cleanup/ValidationRunCleanupServiceTest.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java, ui-validator/src/app/roas/export/export.component.ts
Not sure if we wanted to do this, but have a look, maybe worth it.
See: https://github.com/RIPE-NCC/rpki-validator-3/issues/39
=> Add more details on export #39

rpki-validator/src/main/java/net/ripe/rpki/validator3/api/validationruns/ValidationCheckResource.java, ui-validator/src/app/monitoring-ta/validation-details/validation-details.component.html, ui-validator/src/app/monitoring-ta/validation-details/validation-details.component.scss, ui-validator/src/assets/i18n/en.json
=> Add "seen at" to validation issue list

.dockerignore, .gitlab-ci.yml, Dockerfile
Adds a build for a docker container to the repo.
I decided to go with a build from GitLab CI because this ensures it matches the lifecycle of our other artifacts.
=> Updated docker container

rpki-rtr-server/pom.xml, rpki-validator/pom.xml
=> Systemd service files should not be executable

rpki-rtr-server/src/main/resources/application.properties, rpki-rtr-server/src/main/resources/packaging/generic/conf/application-defaults.properties, rpki-rtr-server/src/main/resources/packaging/generic/conf/application.properties, rpki-validator/src/main/resources/packaging/centos7/etc/rpki-validator-3/application.properties, rpki-validator/src/main/resources/packaging/deb/etc/rpki-validator-3/application.properties, rpki-validator/src/main/resources/packaging/generic/conf/application.properties
If accepted this should fix #166.
=> Improve the wording of listen address config property

.github/workflows/maven.yml
Testing to see if github actions available for our project now GitHub changed the billing plans.
=> Try actions again

rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roas/ExportsController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/RoaPrefixDefinition.java
Bug reported here
https://github.com/RIPE-NCC/rpki-validator-3/issues/185
=> Use SLURM rules for export.{csv/json}

rpki-validator/src/main/java/net/ripe/rpki/validator3/api/ignorefilters/IgnoreFilterDto.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/ignorefilters/IgnoreFilterService.java
It is to fix 
https://github.com/RIPE-NCC/rpki-validator-3/issues/194
=> Fix NPE happening for ignore filters with skipped ASN or prefix.

rpki-validator/src/main/java/net/ripe/rpki/validator3/api/health/HealthController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/background/BackgroundJobs.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/background/ValidationScheduler.java
Fixes #212 
Seems stable in a quick test with
```for i in $(seq 10); do mvn clean test; done;```
=> Do not run background jobs during testsuite

Dockerfile
* Use S6 overlay for process management
* Use ADD instead of build so you can use URLs in build
* Use RPKI user
* Chown data and config dir on startup
* Clean up xodus lockfile on startup
=> Use S6 container overlay so container exits properly

rpki-rtr-server/src/main/resources/packaging/generic/conf/application-defaults.properties, rpki-validator/src/main/resources/packaging/centos7/etc/rpki-validator-3/application.properties, rpki-validator/src/main/resources/packaging/deb/etc/rpki-validator-3/application.properties, rpki-validator/src/main/resources/packaging/generic/conf/application.properties
=> Move application version to different property file

rpki-validator/src/main/java/net/ripe/rpki/validator3/util/HappyEyeballsResolver.java
=> Log happy eyeballs resolver at debug level

rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, rpki-validator/src/main/resources/application.properties, rpki-validator/src/main/resources/packaging/generic/conf/application-defaults.properties, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java
=> Expose strict properties

rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/ValidatedRpkiObjects.java
This saves a round-trip to the Xodus store to retrieve ROAs and router certificates after a successful validation run.
=> Accumulate ROA prefixes and router certificates during TA validation

rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/xodus/XodusIxMap.java
We were already loading the old value from the store anyway so comparing it with the new value should be cheap. Hopefully this reduces the growth of the (log-structured) Xodus data store.
=> Only store value if it is different from old value

rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java
Similar to the RRDP snapshot streaming parsing, this loads objects in batches of 1 MB. Two passes are made over the file system directory, first for all non-manifest objects and the second for all the manifests. This to ensure that every object referenced from a manifest will be in the data store when validating.
=> Rsync batched loading

rpki-parent/pom.xml, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/util/Dates.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/config/ValidationConfig.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, ui-validator/src/app/monitoring-ta/validation-details/validation-details.component.html, ui-validator/src/assets/i18n/en.json
This is to 
a) Fix 'Seen at' so that it show UTC time of when the error was seen
b) Fix the 'strict' mode using rpki-commons-1.13 so that we don't have 'paranoid' mode (complain about objects 7 hours before they expire).
=> Fix error time reporting

rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/ta/TrustAnchorsFactory.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java
Supports better strict mode checking as defined by the RFC 6486bis (section 6, https://tools.ietf.org/html/draft-ymbk-sidrops-6486bis-00#section-6).
If any object on the manifest fails validation the manifest is considered invalid and no ROAs, router certificate, or child CAs will be processed.
Other checks (such as file name checking, issuing a warning, falling back to previous results, etc) are not part of this PR.
=> Fail manifest validation if any listed object fails to validate

rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
All existing RPKI repositories for the trust anchor are pre-loaded
when tree validation starts. This means they are no longer
`registered` during the validation process and their last referenced
at timestamp is not updated. At some point the repository cleanup job
will then delete these repositories from the store.
This causes tree validation to no longer start (since it is only
triggered by a repository update), resulting in the data for the trust
anchor to be no longer updated.
Fixed by no longer pre-loading the repositories and let the regular
validation process register the repositories as needed. Any
repositories that are no longer referenced will be deleted at some
point.
=> Existing RPKI repository "referenced at" is not updated by validation

.gitlab-ci.yml, Dockerfile.rtr-server, Dockerfile.validator, rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/adapter/validator/RefreshCacheController.java, rpki-rtr-server/src/main/resources/application.properties, rpki-rtr-server/src/main/resources/packaging/generic/conf/application-defaults.properties
Upon user request, docker image for rtr server.
Based on the validator image.
Changes some logging to make the behaviour of the rtr server easier to understand (please run it locally to see).
=> Add docker image for rtr server

rpki-parent/pom.xml, rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/retrieval/TrustAnchorRetrievalService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/util/TrustAnchorLocator.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/ta/TrustAnchorsFactory.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/rrdp/Objects.java
File system names and indexed location names are not handled in a case insensitive manner as this probably opens up a whole new can of worms when running on case insensitive file systems, etc. So the same is true for the URI index in `RpkiRepositoriesStore`.
=> Case insensitive URI schemes

rpki-parent/pom.xml, rpki-rtr-server/pom.xml, rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/RtrServerApplication.java
Figured out why my compiler threw a NullPointerException yesterday. With the line below the error was pretty obvious.
```
mvn -Dmaven.compiler.forceJavacCompilerUse=true clean package
```
=> Spring boot 2.4.0

rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/validation/ValidationCheck.java, rpki-validator/src/main/resources/messages.properties, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/ta/TrustAnchorsFactory.java
Or at least close: if they are within 60 seconds we validate. Otherwise we warn. Once CAs fix their code we can become more strict.
=> Validate CRL and manifest next update times are the same

ui-validator/src/app/monitoring-ta/monitoring-ta.component.html, ui-validator/src/assets/i18n/en.json
=> Remove confusing validation status row on trust anchor status page

rpki-parent/pom.xml
Use rpki-commons-1.18 which contains updated dependencies. This branch should trigger CI
=> rpki-commons-1.18

rpki-parent/pom.xml, rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/RtrServer.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpPreviewController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpPreviewService.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/ignorefilters/IgnoreFiltersController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roaprefixassertions/RoaPrefixAssertionsController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roas/ValidatedRoasController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/rpkirepositories/RpkiRepositoriesController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/api/trustanchors/TrustAnchorController.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/impl/ValidationRunsStore.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/util/HappyEyeballsResolver.java, rpki-validator/src/main/java/net/ripe/rpki/validator3/util/TrustAnchorLocator.java, rpki-validator/src/main/resources/packaging/generic/workdirs/preconfigured-tals/apnic.tal, rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/ta/TrustAnchorsFactory.java, rpki-validator/src/test/java/net/ripe/rpki/validator3/rrdp/Objects.java
Just a WIP: Would need a release of commons before this can be merged.
=> Changes needed to work with RPKI commons 1.21

rpki-validator/pom.xml, rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/HttpRrdpClient.java
Remove the sole commons-io usage I could find. Closes #320
=> Remove the usage of commons-io
