RIPE-NCC/rpki-validator-3

- src/main/java/net/ripe/rpki/validator3/adapter/jpa/JPARpkiObjects.java
- src/main/java/net/ripe/rpki/validator3/domain/RpkiObject.java
- src/main/java/net/ripe/rpki/validator3/domain/RpkiObjectCleanupService.java
- src/main/java/net/ripe/rpki/validator3/domain/RpkiObjects.java
- src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java
- src/main/resources/application.properties
- src/main/resources/db/migration/V3__domain.sql
- src/test/java/net/ripe/rpki/validator3/domain/RpkiObjectCleanupServiceTest.java
- src/test/java/net/ripe/rpki/validator3/domain/TrustAnchorsFactory.java
- src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java
RPKI objects that are (no longer) referenced from current manifests
are deleted after at least 7 days of unreachability.
> DB-1174: delete RPKI objects that are not referenced from manifests

- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/RtrServer.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/adapter/netty/PduCodec.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/RtrDataUnit.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/RtrPrefix.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/CacheResetPdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/CacheResponsePdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/EndOfDataPdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/ErrorCode.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/ErrorPdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/IPv4PrefixPdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/IPv6PrefixPdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/NotifyPdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/Pdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/ProtocolVersion.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/ResetQueryPdu.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/RtrProtocolException.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/pdus/SerialQueryPdu.java
- rpki-rtr-server/src/test/java/net/ripe/rpki/rtr/RtrServerTest.java
- rpki-rtr-server/src/test/java/net/ripe/rpki/rtr/domain/pdus/PduTest.java
Implements protocol version 0 including fallback when a version 0 client connects.
When merging with the router key branch the router PDUs should not write anything for protocol version 0, since this version does not support these PDU types.
> RTR protocol version 0

- rpki-rtr-server/pom.xml
- rpki-rtr-server/src/main/resources/packaging/centos7/etc/rpki-rtr-server/application-defaults.properties
- rpki-rtr-server/src/main/resources/packaging/centos7/etc/rpki-rtr-server/application.properties
- rpki-rtr-server/src/main/resources/packaging/centos7/usr/bin/rpki-rtr-server.sh
- rpki-validator/pom.xml
- rpki-validator/src/main/java/net/ripe/rpki/validator3/Validator3Application.java
- rpki-validator/src/main/resources/packaging/centos7/etc/rpki-validator-3/application-defaults.properties
- rpki-validator/src/main/resources/packaging/centos7/etc/rpki-validator-3/application.properties
- rpki-validator/src/main/resources/packaging/centos7/usr/bin/rpki-validator-3.sh
Internal properties are configured in the
classpath:/application.properties file. Default properties are
specified in /etc/`app`/application-defaults.properties. They can be
overriden in /etc/`app`/application.properties.
The RPM still specifies /etc/`app`/application-defaults.properties as
a configuration file, which may be a problem when the
user (accidentally) modifies this file.
> DB-1367: add separate files with internal and default properties

- rpki-validator/src/main/java/net/ripe/rpki/validator3/adapter/jpa/JPARpkiObjects.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/rpkiobjects/RpkiObjectController.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/EncodedRpkiObject.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/RpkiObject.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/RpkiObjects.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/ValidatedRpkiObjects.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/cleanup/RpkiObjectCleanupService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/main/resources/db/migration/V9__encoded_rpki_object.sql
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java
This way the encoded objects can be queried separately from the
Hibernate session and can be garbage collected separately.
> Store encoded RPKI objects in separate place

- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpPreviewService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/health/Health.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/health/HealthController.java
It is some initial version of the healthcheck, required by the this issue
https://github.com/RIPE-NCC/rpki-validator-3/issues/41
We will, most probably, extend it, but for now it returns
- status of the DB -- if it's sane and can run a query
- statuses of the TAs -- if the first repository validation is completed for each of them
- statuses of BGP dumps -- if they are present and not too old.
> Add healthcheck

- rpki-validator/src/main/java/net/ripe/rpki/validator3/adapter/jpa/JPARpkiRepositories.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/adapter/jpa/JPATrustAnchors.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/background/TrustAnchorValidationJob.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java
Fix for slow startup of rsync repositories, Afrinic and LACNIC in particular. If a TA has a prefetch.url, we synchronously prefetch the repository, before starting certificate tree validation.
> Fix slow rsync init

- rpki-validator/Changelog.txt
- rpki-validator/pom.xml
- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImpl.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/xodus/XodusImpl.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/util/HappyEyeballsResolver.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/util/Http.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/benchmarks/FSTraversalTest.java
This is a simplistic implementation of "happy-eyeballs" as described in RFC8305, but without sorting candidate IPs and caching results. Still falls back to v4 if v6 is broken, so could be released.
> Implement happy-eyeballs as a jetty http client's address resolver

- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/ignorefilters/IgnoreFiltersController.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roas/ObjectController.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/trustanchors/TrustAnchorService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorState.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/ValidatedRpkiObjects.java
This is to address the issue https://github.com/RIPE-NCC/rpki-validator-3/issues/124
We decide that "/api/objects/validated" should return "ready: true" only if for every TA
- if initial validation run has completed (behaviour before)
- if there're no repositories with status PENDING, related to this TA.
Also, remove "links" attribute from ROAs returned by this end-point, nobody cares about them.
> To decide if certain TA is "ready" check

- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/util/InstantWithoutNanos.java
When CI starts working it will catch missing license headers.
> Add missing header

- pom.xml
- rpki-parent/pom.xml
- rpki-rtr-server/pom.xml
- rpki-validator/pom.xml
- ui-validator/pom.xml
...enterprise style build, which now makes us use rpki-commons-1.7.3
* parent pom is inherited by children
* properties can be defined in the parent pom
* dependencies and repositories can be defined by parent
* _version_ of dependencies for children can be set through `<dependencymanagement />`
I also moved a jar to the test scope since I assumed it was test only.
> Add parent pom and use rpki-commons-1.7.3

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
Fixes a missing parameter, causing messages like `Manifest https://rpki.cnnic.cn/rrdp/notify.xml for this certificate is not available at repository {1}.`.
> Include the manifest URL in the log message

- rpki-rtr-server/pom.xml
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/RtrCache.java
- rpki-validator/Changelog.txt
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpRisDownloader.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/metrics/HttpClientMetricsService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/metrics/TrustAnchorMetricsService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/HttpRrdpClient.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/util/Http.java
Metrics for HTTP status codes (and error messages). Example metrics:
```
http_response_status_total{status="200",url="https://rrdp.apnic.net/",} 1.0
http_response_status_total{status="200",url="https://www.ris.ripe.net/",} 2.0
http_response_status_total{status="javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure",url="https://rrdp.ripe.net/",} 1.0
```
This should help me debug the amount of SSLHandshakeExceptions…
> Add http status code as prometheus metrics

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/metrics/HttpClientMetricsService.java
The histogram was calculated over one minute, which often does not contain any requests.
We now use a six hour window and will monitor memory usage.
> Calculate percentiles over last six hours

- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpRisDownloader.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/metrics/HttpClientMetricsService.java
Cause was empty for `HttpStatusException`. Now we handle `Http.Failure`'s without a cause properly.
This may cause some unique log messages (and transitively unique metrics in prometheus). I'll keep an eye on that.
> Unwrap sub-type of exception first

- rpki-validator/src/main/resources/application.properties
- rpki-validator/src/main/resources/packaging/generic/conf/application-defaults.properties
Changes the number of peers to be equal to the threshold used by ripestat.
> Raise the RIS visibility threshold to ten peers

- rpki-parent/pom.xml
No security implications because Hikari is not on classpath. Keeps
a dark cockpit in whitesource.
> Bump spring boot version for new Jackson version

- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roas/ExportsController.java
- ui-validator/src/app/roas/export/export.component.ts
- ui-validator/src/assets/i18n/en.json
UI still expect export-extended backend to exist, while backend is renamed to roas-only.
I remember we renamed because we don't include SLURM on the extended.
Now this change revert backend API path, and include slurm on extended, without
additional info.
{
"asn" : "12314",
"prefix" : "192.168.0.0/24",
"maxLength" : 24,
"ta" : "SLURM",
"notBefore" : "",
"notAfter" : "",
"serialNumber" : ""
}
> Fix export-extended

- .gitlab-ci.yml
Possible fix for setting the version of artifacts to match the git tag
> Set release version from tag

- rpki-validator/pom.xml
Plain bump to the latest xodus version.
From [the changelog](https://youtrack.jetbrains.com/releaseNotes?q=%23XD%20%23Resolved%20Fix%20versions:%201.3.232&title=1.3.232):
```
XD-768 — Performance degradation and OOM crash while sequentially process large transactions
```
There is also the new "soft-reference cache" [feature](https://youtrack.jetbrains.com/issue/XD-799) which would need configuration.
> Bump xodus version to 1.3.232

- Dockerfile
Fixes the build in CI.
ADD with a path:
`artifacts/foo.tar.gz` -> `/tmp/artifacts/foo.tar.gz`
`basename artifacs/foo.tar.gz`: `foo.tar.gz`
ADD with a url:
`https://example.org/subdir/foo.tar.gz` -> `/tmp/foo.tar.gz`
`basename https://example.org/subdir/foo.tar.gz`: `foo.tar.gz`
COPY with a path (no url support):
`artifacts/foo.tar.gz` -> `/tmp/foo.tar.gz`
Decided to just use COPY again.
> Use copy to add artifact to docker image

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/retrieval/TrustAnchorRetrievalService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/TrustAnchor.java
- rpki-validator/src/main/resources/messages.properties
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationServiceLocationTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationServiceTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/storage/data/TrustAnchorTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/util/ValidateProvidedTrustAnchorTest.java
Quick and slightly dirty implementation of fallback behaviour. Would like it if the implementation is slightly cleaner.
> Fallback to rsync from https when trust anchor certificate can not be loaded

- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/RtrCache.java
- rpki-rtr-server/src/main/java/net/ripe/rpki/rtr/domain/RtrClients.java
- rpki-rtr-server/src/test/java/net/ripe/rpki/rtr/RtrServerTest.java
- rpki-validator/Changelog.txt
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/metrics/HttpClientMetricsService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/metrics/TrustAnchorMetricsService.java
* Rename prometheus metrics to they follow the naming best
practices [0].
* Track the number of rtr server connections.
[0]: https://prometheus.io/docs/practices/naming/
> Rename prometheus metrics to follow best practices and track rtr connections

- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImpl.java
RPKI objects are automatically removed by the RpkiObjectCleanupJob, so there is no need to remove anything when a delta withdrawal is processed.
Removing the object on withdrawal (or update) should not be done since the object can also be published by another repository(rsync or rrdp) or a malicious RRDP server can fake a withdrawal.
> Ignore RRDP delta withdrawal

- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/xodus/Xodus.java
Gathering the stack trace is very expensive. Remove this speeds up the validation process by about 10%-30%.
> Don't store stack trace for transaction

- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/xodus/XodusImpl.java
Makes xodus use soft references for it's cache instead of a fixed
partition. This is documented in [0]. It is said to solve an issue [1]
where sequential writes fail due to out of memory.
[0]: https://youtrack.jetbrains.com/issue/XD-799
[1]: https://youtrack.jetbrains.com/issue/XD-768
> Use Xodus logcache based on soft references

- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/SearchTerm.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/Sorting.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpPreviewService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roaprefixassertions/RoaPrefixAssertionEntity.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roaprefixassertions/RoaPrefixAssertionsController.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roaprefixassertions/RoaPrefixAssertionsService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/roas/ValidatedRoasController.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/RoaPrefixAssertion.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/ValidatedRoaPrefix.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/ValidatedRpkiObjects.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/api/SearchTermTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/api/bgp/BgpPreviewServiceTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/BgpPreviewEntryTest.java
Shares ROA prefix instances between `BgpPreviewService` and `ValidatedRpkiObjects` and stores the `BgpPreviewEntry` data more efficiently. Together heap usage is reduced by about 75 MB.
> Reduce BGP preview memory usage

- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/xodus/XodusImpl.java
The default log cache page size in Xodus is 64 KB. This is useful when
data that is used together is stored near eachother. However, in RPKI
most objects are addressed by the SHA-256 value of the object. This is
basically "random" so we do not get any advantage when loading objects
that are nearby to the object we're currently interested in.
Reducing this log page cache size to 2 KB ensures almost all RPKI
objects still fit and we do not waste CPU and memory loading
co-located objects that are very unlikely to be needed.
With this setting I've been able to run the RPKI validator with the
five RIR trust anchors for more than 13 hours using 512 MB maximum
heap size without issue. Much better than the current required 1536 MB
max heap size!
JVM options used: `-verbose:gc …
> Reduce Xodus memory usage by using a smaller log cache page size

- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpPreviewService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpRisDownloader.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/bgp/BgpRisDump.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/api/bgp/BgpPreviewServiceTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/api/bgp/BgpRisDownloaderTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/api/bgp/BgpRisParsingTest.java
Greatly reduced temporary memory usage during BGP RIS download. For example, the `IdentityMap` holding parsed prefixes was retaining around 150 MB of memory. Now we immediately transform the BGP RIS entries into memory optimized BgpRisPreviewEntry objects so we no longer need this.
With this change it is possible to start and run the validator with `-Xmx384m`, at least for a while with an initialized object cache.
> BGP RIS download streaming parser

- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImpl.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImplTest.java
By default only four RRDP snapshots or deltas will be processed at the same time. This is to limit the peak memory usage.
The `rpki.validator.rrdp.repository.parallelism` property can be set to override the default.
> Limit RRDP processing parallelism

- rpki-validator/src/main/java/net/ripe/rpki/validator3/util/HappyEyeballsResolver.java
Error logging happens at a higher level when no connection could be established at all. All other connection attempts do not need logging except when debugging the implementation. In this case, just enable trace level for this component.
> Reduce logging from happy eyeballs resolver

- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/xodus/XodusImpl.java
Soft-references ensure that the JVM will not run out of memory because of the Xodus cache, but can still cause a lot of GC work before the soft references are released.
Before the maximum JVM monitoring shows
Notice the GC activity line, which sometimes goes up to 5% and stays there for a few minutes. CPU usage is also very high during this time. According to the time command the process monitored here was using about 150% CPU on average:
```
real	3758m16.149s
user	5423m59.238s
sys	131m41.200s
```
With the maximum set to 10% (of 384 MB heap) the graph changes:
High CPU usage spikes are much lower and probably correspond to certificate tree validation runs. Heap space usage is also more steady. GC activity is always low. CPU usage now averages about 50%:
```
real	1341m32.170s
user …
```
> Limit total Xodus cache size to avoid high GC load

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/ErrorCodes.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/HttpRrdpClient.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpClient.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpParser.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImpl.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/OnDeleteTrigger.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/rrdp/RrdpClientStub.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/rrdp/RrdpParserTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImplTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/storage/IxMapTest.java
Streaming parsing of RRDP snapshots. Objects are committed to the database in batches (1 MB in size) to avoid using too much memory. To avoid referring to objects that are not yet committed manifests are stored last. This is implemented by parsing the snapshot twice. Other approaches added quite a lot of complication (updating the AKI MFT index only at the end) or used too much memory (keeping all manifests in memory until the end).
> Rrdp streaming parser

- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImpl.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImplTest.java
Similar to parallel parsing in the rsync implementation of https://github.com/RIPE-NCC/rpki-validator-3/pull/246
> Parse RRDP snapshot RPKI objects in parallel for improved performance

- rpki-parent/pom.xml
- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/rpkiobjects/RpkiObjectController.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/RpkiObjectUtils.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/RpkiObject.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/TrustAnchor.java
The validator does not use or store passing checks but they take up a
lot of memory during validation. Without storing these checks the peak
memory usage of the validator is reduced.
With all the other fixes (streaming RRDP, incremental rsync import)
the validator can now run with maximum heap size of 256 MB with
the five RIR trust anchors.
> Do not store passing checks

- Dockerfile
* Switch base image to library/openjdk, fixes #250.
* Move rsync directory to data path.
> Switch base image to openjdk, move rsync to data path

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/ErrorCodes.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImpl.java
Some of these thrown RrdpException needs to be monitored. Especially corrupt rrdp snapshot.
> Corrupted snapshot must be monitored and used to trigger alert

- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImpl.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/util/HttpStreaming.java
See if this fixes a problem with "hanging" RPKI validators.
Normal case there will be very few deltas for a single RRDP
repository. When there are many it is useful to ensure that the first
delta is downloaded and processed first as it doesn't make sense to
download additional ones when the first one is stick for some reason.
> Http streaming timeouts and sequental RRDP downloading

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImpl.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/rrdp/RrdpServiceImplTest.java
The write transaction wasn't needed in this case until all objects
were converted anyway.
Holding the write transaction lock could result in a deadlock if the
common fork-join pool is full of blocked threads (shouldn't happen...)
waiting for Xodus (read or write).
In general we should avoid accessing Xodus from the common fork-join
pool, this should also avoid this issue completely.
> Avoid holding write transaction lock while accessing fork-join pool

- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/xodus/Xodus.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/util/ForkJoin.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/util/HttpStreaming.java
Xodus transactions and HTTP downloads are (potentially) blocking. If
we accidentally call these from the fork join pool it may cause the
pool to be exhausted. By using the `ForkJoinPool#managedBlock` API
additional threads will be created if needed.
> Notify fork join pool of blocking operations

- rpki-validator/src/main/java/net/ripe/rpki/validator3/api/trustanchors/TrustAnchorService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/background/BackgroundJobs.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/background/RpkiRepositoryCleanupJob.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/background/ValidationScheduler.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/cleanup/RpkiRepositoryCleanupService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/RpkiRepositoryValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorState.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/TrustAnchorValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/RpkiRepository.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/encoding/custom/RpkiRepositoryCoder.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/RpkiRepositories.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/stores/impl/RpkiRepositoriesStore.java
- rpki-validator/src/main/resources/application.properties
- rpki-validator/src/main/resources/packaging/deb/etc/rpki-validator-3/application.properties
- rpki-validator/src/main/resources/packaging/generic/conf/application-defaults.properties
- rpki-validator/src/main/resources/packaging/generic/conf/application.properties
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/cleanup/RpkiRepositoryCleanupServiceTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/storage/encoding/custom/RpkiRepositoryCoderTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/storage/stores/impl/RpkiRepositoriesStoreTest.java
Track the time that a repository was last referenced during a validation run. Once a repository hasn't been referenced for at least `rpki.validator.rpki.repository.cleanup.grace.duration` it will be deleted. Deleted RRDP repositories will also be removed from the validation scheduler.
Best way to review is probably by going through each commit separately.
> RPKI repository cleanup job

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/xodus/Xodus.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/util/ForkJoin.java
Ensures we no longer take up all the spare threads in the common fork-join pool that can cause `RejectedExecutionExceptions`. 
I'm not sure of all this is worth the trouble. The validator worked before without any `blocking` implementation so an alternative is to just remove this whole concept for simplicity.
> Maximize managed blocker threads

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/ValidatedRpkiObjects.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/api/SearchTermTest.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/api/bgpsec/BgpSecFilterServiceTest.java
The code relies a bit less on side-effects and the validation
functions now return a result instead of mutating an accumulator.
All certificate authorities are validated, even when a manifest
contains errors in strict mode. However, the results of the validation
are not kept. This way we avoid having keep child certificates in
memory or to parse the manifest entries twice (first to discover
errors in the manifest, then to process the children).
> Use depth-first CA validation to reduce memory usage

- ui-validator/src/app/core/footer/footer.component.html
- ui-validator/src/app/core/footer/footer.component.ts
- ui-validator/src/assets/i18n/en.json
- ui-validator/src/assets/i18n/fr.json
The version is downloaded from the '/api/healthcheck' end-point.
> Add current validator version to the UI footer.

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/ta/TrustAnchorsFactory.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java
The validation is not strictly correct since the object may have
already been removed from the original location, but we will still
validate it.
> Validate that RPKI repository object was found at the correct location

- rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/data/RpkiObject.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/ta/TrustAnchorsFactory.java
Results in some objects with warnings in the UI:
These are all warnings about the format of the subject and issuer DN not being correct. This is caused by the use of a ASN.1 DER `UTF8String` instead of `PrintableString`. The latter is required by the RFCs.
When https://github.com/RIPE-NCC/rpki-commons/pull/26 is merged we'll also see many warnings on the presence of the id-ad-rpkiNotify access method in EE certificates.
> Do not ignore validation warnings for RPKI objects stored in the cache

- rpki-validator/src/main/java/net/ripe/rpki/validator3/background/BackgroundJobs.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/background/Throttled.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/background/ValidationScheduler.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/background/ThrottledTest.java
Fixes two causes of long delays in the bootstrapping process:
1. Triggering already running certificate tree validations were ignored. So if a repository was updated while a validation is already running it could take 10+ minutes before the certificate tree validation was run again, based on the frequency of repository updates. Now the trigger is remembered and the validation will be scheduled again after the current run completes. The minimum time between validation runs was also reduced, as it is mainly used to avoid quickly triggering multiple runs.
2. The database was only checked once every 5 minutes for PENDING rsync repositories. Now we check every minute.
Together these changes result in a bootstrap time between 3-4 minutes (also depending on network speed, etc) using the 5 RIR …
> Decrease bootstrap time to first validation

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/ErrorCodes.java
- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/main/resources/application.properties
- rpki-validator/src/main/resources/messages.properties
- rpki-validator/src/main/resources/packaging/generic/conf/application-defaults.properties
Adds a warning when a manifest is invalidated due to the presence of an invalid object.
Currently the differences between strict or non-strict is about 94 ROA prefixes using the trust anchors displayed below:
Three manifests from APNIC become invalid (from https://rpki.cnnic.cn/) and one ROA from RIPE NCC due to an elapsed manifest next update time (from rsync://rpkica.mccay.com/). 
The affected ROAs are:
> "132168","2402:1440::/32","48","APNIC RPKI Root","2020-10-13T14:05:00Z","2021-04-29T06:55:15Z","1236"
> "13444","103.221.92.0/22","24","APNIC RPKI Root","2020-05-09T08:36:19Z","2021-04-29T06:55:15Z","2622"
> "138527","103.221.16.0/22","24","APNIC RPKI Root","2020-07-13T10:44:09Z","2021-04-29T06:55:15Z","2986"
> "138527","103.221.20.0/22","24","APNIC RPKI …
> Default to strict validation

- rpki-parent/pom.xml
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/ta/TrustAnchorsFactory.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java
Using rpki-commons 1.17-SNAPSHOT from the https://github.com/RIPE-NCC/rpki-commons/pull/35 PR.
Fixes test cases related to stricter manifest entry filename validation.
> Updated manifest entry filename validation

- rpki-validator/src/main/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationService.java
- rpki-validator/src/test/java/net/ripe/rpki/validator3/domain/validation/CertificateTreeValidationServiceTest.java
If included objects fail validation, only drop the failed objects, not
all objects on the manifest. The main intent is to prevent MITM
attacks where an attacker replaces or removes objects from the
publication point. Checking that all manifest entries are present and
the hashes match prevents this.
Bugs in the CA or publication server that cause invalid objects to be
published (with the correct hash on the manifest) will not be
prevented and will not cause all objects to become invalid.
> Only fail the entire manifest when entry hashes do not match

- rpki-validator/Changelog.txt
- rpki-validator/src/main/resources/packaging/generic/conf/application-defaults.properties
* Faster removal of repositories not referenced by a validation run: 2
days.
* Increase default RRDP update interval to ten minutes.
Addresses/Fixes #307.
@erikrozendaal can you double check that this is safe? I am uncertain about the behaviour in the setting where a parent and child repository update very infrequently (i.e. > two days)and do not need to be revalidated, which is the moment at which we update reachability.
For terminology:
```
+------------+
| Parent     |
| repository |
+------------+
|
|
v
+------------+
| Child      |
| repository |
+------------+
```
> Relax update intervals

- rpki-parent/pom.xml
- rpki-validator/Changelog.txt
As a software engineer I want to exclude xstream from the transitive dependencies so I do not get spurious alerts about vulnerabilities in a unused transitive dependency.
> Remove xstream as transitive dependency

- rpki-validator/src/main/resources/packaging/generic/workdirs/preconfigured-tals/apnic.tal
- rpki-validator/src/main/resources/packaging/generic/workdirs/preconfigured-tals/lacnic.tal
lacnic tal from https://www.lacnic.net/4984/2/lacnic/rpki-rpki-trust-anchor
> Update LACNIC and APNIC tal to use HTTPS
